### ISSUE TITLE
[Bug] Pipeline editor throwing Error

### ISSUE THREAD

**Issue by Safvan-tsy** [instill-ai/instill-core#1124]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Are you willing to own the issue?

- [X] I can own this issue

### Where did you encounter this bug?

Instill Cloud

### Describe the Bug

Instill cloud >> create a pipeline or edit a pipeline >> Throwing the below exception (ss attached)
![Screenshot from 2024-10-02 14-27-48](https://github.com/user-attachments/assets/4ae41211-3d3e-46d2-b104-35faba7bf574)

**Comment by kuroxx** [comment]
Hi @Safvan-tsy thank you for raising this issue, could you confirm if this bug still persists or if it has been resolved now? Thank you 🙏

**Comment by Safvan-tsy** [comment]
Hey @kuroxx . Its not resolved i'm still facing the same issue

**Comment by kuroxx** [comment]
Thanks for updating me @Safvan-tsy, let me check with our team internally and get back to you soon!

**Comment by donch1989** [comment]
Hi @Safvan-tsy 
I'm wondering about which browser you're using. It'll help use to identify the problem. Thanks!

**Comment by EiffelFly** [comment]
A side question is, can you go to your previous created pipeline?

**Comment by Safvan-tsy** [comment]
Hey @donch1989 

Browser:
 Google Chrome Version 129.0.6668.70 (Official Build) (64-bit)

OS:
 Ubuntu 22.04.5 LTS  jammy

**Comment by Safvan-tsy** [comment]
hey @EiffelFly  no ican't

**Comment by EiffelFly** [comment]
@Safvan-tsy Did you still experience the same bug? We have implemented some fixes could you help us double check it 🙏

**Comment by Safvan-tsy** [comment]
I can access the pipeline editor from my firefox . so if this is not reproducible can close this bug

**Comment by EiffelFly** [comment]
Hi @Safvan-tsy That is great. This information is valuable for us

> more info from logs
3480-71d2707d56368dad.js:1 Error: You forgot to wrap your app in <UserProvider> at get user (2564-fd610430ffb76214.js:1:33866) at s (page.bundle.js:1:4386)

https://api.instill.tech/v1beta/component-definitions?page=1&view=VIEW_FULL net::ERR_INTERNET_DISCONNECTED makeMethodRequest @ 6a130808-c03db8803b1ec173.js:1 get @ 6a130808-c03db8803b1ec173.js:1 listComponentDefinitions @ 6a130808-c03db8803b1ec173.js:1 listComponentDefinitions @ 6a130808-c03db8803b1ec173.js:1Understand this error layout-2a56d04df9fdce6a.js:1 error in retry TypeError: Failed to fetch

About this I will take a look deeper, what about your Google Chrome now? Can you access our product with it now? (We have several fixes recently)
